spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: d04m07a1997
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  spring:
    data:
      mongodb:
        uri: mongodb+srv://dapevi1997:d04m07a1997@sofka-cluster.as4znqn.mongodb.net/bike?retryWrites=true&w=majority

